# docker-compose for AuthC development stack
version: '3.8'

services:
  api:
    build: .
    container_name: authc-server
    env_file:
      - .env
    environment:
      - SMTP_HOSTNAME=mailhog
      - SMTP_PORT=1025
    volumes:
      - ./db/:/app/db/
    ports:
      - 127.0.0.1:3002:3002
# Optional SMTP mail catcher for testing account recovery emails. Inbox UI is available on 8025
  mailhog:
    container_name: mailcatcher
    image: mailhog/mailhog
    entrypoint: ["/bin/sh", "-c", "MailHog &>/dev/null"]
    ports:
      - 8025:8025