# docker-compose for development stack
version: '3.8'

services:
  api:
    build: .
    container_name: authc-api
    env_file:
      - .env
    restart: always
    volumes:
      - ./db/users.db:/app/db/users.db
    ports:
      - 127.0.0.1:3002:3002